### PR TITLE
Add patch from Issue #2636490 for Panels IPE usability improvements

### PR DESCRIPTION
**Pull request by saltednut**

### CODE REVIEW

**Comment by balsama** [comment]
I couldn't get this patch to apply to beta4 or dev-8.3.x (or our heavily patched version of beta4 - but we should start with dev-8.3.x probably before we worry about that)

**Comment by balsama** [comment]
hm. I take that back. It does apply to head. Just not to beta4 (not surprising).

We can't chase head in lightning though, so we'll need some way to get this to apply. Preferably to our heavily patched version of beta4. One possible solution is to make [this](https://github.com/acquia/lightning/blob/8.x-1.x/composer.json#L52) patch even bigger and bring it all the way up to head. But that seems extreme.

**Comment by saltednut** [comment]
As long as you apply this patch AFTER your mega-patch, it should work fine. Did you try that?

**Comment by brantwynn** [comment]
As long as you apply this patch AFTER your mega-patch, it should work fine.
Did you try that?

On Thu, Jun 2, 2016 at 1:55 PM, Adam Balsam <notifications@github.com>
wrote:

> hm. I take that back. It does apply to head. Just not to beta4 (not
> surprising).
>
> We can't chase head in lightning though, so we'll need some way to get
> this to apply. Preferably to our heavily patched version of beta4. One
> possible solution is to make this
> <https://github.com/acquia/lightning/blob/8.x-1.x/composer.json#L52>
> patch even bigger and bring it all the way up to head. But that seems
> extreme.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/acquia/lightning/pull/124#issuecomment-223387877>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ABDTPnP48HPZ4lk-cQLoQA4GThQwcBRDks5qHyc0gaJpZM4IsoDv>
> .
>



-- 

*Brant Wynn*Technical Lead, Presales | *Acquia
<http://www.acquia.com/?utm_source=Email&utm_medium=Signature&utm_content=Acquia.com&utm_campaign=Acquia%2BEmail%2BSignature>*
*O:* +1 617-588-9933 | *M:* +1 312-607-9430 | @brantwynn
<http://twitter.com>
Demo Drupal as an Enterprise-ready solution <http://acquia.com/downloads/df>

Start Building Drupal Sites on Acquia Cloud for Free!
<http://acquia.com/free>

**Comment by balsama** [comment]
Yeah. The mega patch only brings panels up to commit 8eba1a0. Must be something after that commit that's needed. Output:

```
  - Applying patches for drupal/panels
    https://www.drupal.org/files/issues/panels--beta4-to-8eba1a0.patch (beta4 to 8eba1a0 - quickedit blocks)
    https://www.drupal.org/files/issues/panels-ipe-esc-focus-fixes-2636490-9.patch (2636490 - IPE's cancel button is easy to mistake for a button to close the tray)
   Could not apply patch! Skipping.
```

**Comment by balsama** [comment]
This was committed to panels and is in beta5, which lightning uses.

**Pull request closed without merging**
