### PR TITLE
Rename "save to media library" field

### PR DESCRIPTION
**Pull request by csirmazbendeguz**
Renames labels in test config files. Prerequisite: renaming labels in lightning_media first.

### CODE REVIEW

**Review by phenaproxima — CHANGES_REQUESTED** [review]
This looks good to me, but it will need an update class. See Drupal\lightning\Update\Update320 for an example. The update, if executed, should make these same changes to every instance of field_media_in_library.

That's in addition to changing the code which actually creates new instances of this field, as well as the instances of it that we ship with default config.

**Comment by csirmazbendeguz** [comment]
Ok, I can't find the Drupal\lightning\Update\Update320 class, but I found other Update classes.

**Comment by csirmazbendeguz** [comment]
I added the Update class to the lightning_media PR. I think it belongs there, because this one only changes the tests' configs.

**Comment by phenaproxima** [comment]
This was fixed in Lightning Media today, closing as duplicate.

**Pull request closed without merging**
