### PR TITLE
Removing wait steps from Behat tests.

### PR DESCRIPTION
**Pull request by grasmash**

### CODE REVIEW

**Comment by grasmash** [comment]
Looks like Travis CI isn't running?

**Comment by phenaproxima** [comment]
This is far more elegant than what we have now. I'm all for it. Big +1 here.

**Comment by grasmash** [comment]
Ug. Behat3 doesn't support scenario tags in afterStep. Only Behat2.

**Comment by grasmash** [comment]
Issue in Drupal Extension upstream:
https://github.com/jhedstrom/drupalextension/issues/92

**Comment by balsama** [comment]
Merged #118. Is there anything left in this PR that wasn't covered there? Or can we close this? @phenaproxima

**Comment by phenaproxima** [comment]
As of #118, we still have some wait steps in tests -- they are occasionally useful. But I was able to remove many of them by defining cohesive steps for certain tasks. IMHO, we can close this.

**Pull request closed without merging**
