### PR TITLE
Adding front end assets to composer.json.

### PR DESCRIPTION
**Pull request by grasmash**
Currently, simply using composer to install lightning will not build the front end dependencies. Drush make must be used, or `npm install` must be called from the lightning directory. This causes automated tests to fail.

This PR uses composer to manage front end dependencies.

### CODE REVIEW

**Comment by grasmash** [comment]
A few notes:
- This PR relies on https://github.com/francoispluchino/composer-asset-plugin/pull/216 being merged upstream
- This notably slows down composer builds, at least on the first run. This is due to npm package information being downloaded. It is cached and subsequent builds are faster.
- We do not have a mechanism to ignore recursive dependencies, such as jquery, jqueryui, and backbone.
- I believe this allows us to remove code. Namely the bower.json file, possibly package.json, and a few Phing targets.

**Comment by grasmash** [comment]
francoispluchino/composer-asset-plugin#216 has been merged upstream. @balsama Can you restart travis tests and see if we get a pass?

**Comment by balsama** [comment]
@grasmash errored: https://travis-ci.org/acquia/lightning/builds/125854511#L512

**Comment by grasmash** [comment]
One more time? :p

**Comment by balsama** [comment]
@grasmash Same result: https://travis-ci.org/acquia/lightning/builds/125854511

**Comment by grasmash** [comment]
Very strange, it's claiming that the underscore package being downloaded is corrupt. Download the same package locally for me is fine. Not sure what would cause that.

**Comment by grasmash** [comment]
https://github.com/francoispluchino/composer-asset-plugin/issues/100

**Comment by balsama** [comment]
hmmm. and PR #119 doesn't have a cache on travis - presumably because it never finished?

**Comment by danepowell** [comment]
See #129 and #131

**Pull request closed without merging**
