### PR TITLE
Update Lightning API to 8.x-4.2

### PR DESCRIPTION
**Pull request by dmlb2000**
This updates lightning api to 4.2 to fix updates to openapi.

Signed-off-by: David Brown <dmlb2000@gmail.com>

### CODE REVIEW

**Comment by phenaproxima** [comment]
See www.drupal.org/project/lightning/issues/3062585.

**Comment by dmlb2000** [comment]
@phenaproxima Seems like there's open pipeline issues with Travis.

**Comment by phenaproxima** [comment]
Yup, we're in the middle of some build system changes over here, sadly. Once those are sorted out, I think I can merge this.

**Comment by dmlb2000** [comment]
@phenaproxima Can I make a suggestion? Try configuring composer to stop printing color output, it really is painful to parse ;)

**Comment by phenaproxima** [comment]
This has been implemented since this PR was filed, so I'm closing it.

**Pull request closed without merging**
