### PR TITLE
Hide the unused "Alternative text" field on image media widget forms

### PR DESCRIPTION
**Pull request by TravisCarden**
See https://www.drupal.org/node/2767213#comment-11454241.

### CODE REVIEW

**Comment by balsama** [comment]
Thanks for this, Travis. This patch also seems to hide the alt text field when uploading an image via the media library in ckeditor though. Which would prevent users from entering alt text for inline images.

create_basic_page___site-install

Can we add an additional check in the form_alter hook to make sure we're on the correct implementation of the form?

**Comment by TravisCarden** [comment]
Ah! Thank you, @balsama. I'll look into it as soon as I have a minute.

**Review by balsama — CHANGES_REQUESTED** [review]
Already noted in the conversation tab, but this patch also seems to hide the alt text field when uploading an image via the media library in ckeditor though. Which would prevent users from entering alt text for inline images.

We'll need to add an additional check in the form_alter hook to make sure we're on the correct implementation of the form or take a different approach.

**Comment by phenaproxima** [comment]
I'm not sure I understand what's gained by suppressing the alt field here. To me, we should fix the underlying problem, which is that Entity Browser can't propagate arbitrary data into the calling window...

**Comment by TravisCarden** [comment]
@phenaproxima fixing the underlying problem is certainly preferable. The approach in this PR was proposed as a stop gap measure to prevent a broken-feeling UX until the underlying problem *could be* fixed.

**Comment by TravisCarden** [comment]
I've had a chance to look at this again, and I don't see that there's any way to distinguish between contexts in the form alter hook. Seems like we need to either find a better implementation for the stop gap or actually fix the underlying problem. I don't have bandwidth to undertake either right now, I'm afraid.

**Comment by ovillarroel** [comment]
Any news about this well-known issue?

**Comment by TravisCarden** [comment]
Old and obsolete.

**Pull request closed without merging**
