### PR TITLE
Moderation sidebar

### PR DESCRIPTION
**Pull request by csirmazbendeguz**
Enable moderation sidebar

### CODE REVIEW

**Comment by csirmazbendeguz** [comment]
This is randomly failing with a database lock exception

**Comment by balsama** [comment]
Huh. Wonder what's up with those. I'll restart now. Also note that this needs to be cherry-picked into the 8.6.0-prerelease branch and the 4.x branch.

**Comment by phenaproxima** [comment]
Pipelines is failing due to running out of memory while running `composer update`.

**Comment by phenaproxima** [comment]
Merged into 8.x-3.x and cherry-picked to 8.x-4.x and 8.6.x-prerelease.

**Pull request merged**
