### PR TITLE
Adding more caching to Travis builds to decrease build time.

### PR DESCRIPTION
**Pull request by grasmash**

### CODE REVIEW

**Comment by grasmash** [comment]
This failure seems unrelated to changes, re-run?

**Comment by grasmash** [comment]
Added a commit to force a rerun.

**Comment by grasmash** [comment]
@phenaproxima Yeah, this is getting the same unrelated Behat failure for the media feature that #80 is getting.

**Comment by balsama** [comment]
Thanks @grasmash! Made us realize that we're not using those ssh hosts anymore too, but good to know that there is a plugin for that. Thanks!

**Pull request merged**
