### PR TITLE
Issue #2822084: Update replication and workspace versions

### PR DESCRIPTION
**Pull request by jeremdow**
Require newer alphas to prevent conflicts:
drupal/replication: 8.1.0-alpha5, drupal/workspace: 8.1.0-alpha4

Replication patch #28140055 still applies.

Workspace #2791789 no longer needed.

### CODE REVIEW

**Comment by phenaproxima** [comment]
Thank you for this PR.

I'm sorry to say that this is blocked for a few hours. It will not pass Travis due to a minor snafu in our testing infrastructure. I'll be fixing that as part of #192, then when that is merged, I'll merge #191, which updates Replication. When both of those are merged, you'll need to pull upstream changes into your PR branch. While you're at it, feel free to update Multiversion as well, it looks like they tagged alpha12 :)

**Comment by jeremdow** [comment]
Okay, will do - thanks.

**Comment by phenaproxima** [comment]
#192 is now merged. Once #191 is merged, you'll want to pull changes. There will be merge conflicts with composer.lock -- just delete composer.lock and run composer update to regenerate it. You will also need to run "phing package" (you'll need Phing installed) to update the Drush make files.

**Comment by jeremdow** [comment]
Okay, I see the drush make file now too, thanks.

**Comment by phenaproxima** [comment]
#191 has also been merged. Go nuts!

**Comment by jeremdow** [comment]
--- Failed scenarios:
    tests/features/panelizer_revisions.feature:4

Seems unrelated?

**Comment by phenaproxima** [comment]
That particular one looks to be a random failure, but this PR is still breaking all Travis builds. We've seen this before -- Multiversion does some weird stuff to the node/%/revisions page that causes at least one of our tests to fail. Try removing the Multiversion update and seeing if that fixes things.

**Comment by jeremdow** [comment]
Trying with alpha11 - that one still has the entity_storage_migrate dependency they just removed from workspace, that may need to rollback too then.

**Comment by jeremdow** [comment]
I think this is as close as I can get with this - 

`--- Failed scenarios:
    tests/features/media/browser.feature:44`

Am I reading the failures right?

But I definitely need workspace alpha4, or I get below when installing relaxed (any version?):

`Fatal error:  Declaration of Drupal\relaxed\CouchdbReplicator::replicate(Drupal\workspace\WorkspacePointerInterface $source, Drupal\workspace\WorkspacePointerInterface $target, $task = NULL) must be compatible with Drupal\workspace\ReplicatorInterface::replicate(Drupal\workspace\WorkspacePointerInterface $source, Drupal\workspace\WorkspacePointerInterface $target, Drupal\replication\ReplicationTask\ReplicationTaskInterface $task = NULL) in /app/web/modules/contrib/relaxed/src/CouchdbReplicator.php on line 20`

**Comment by jeremdow** [comment]
`--- Failed scenarios:
    tests/features/workflow/scheduled_updates.feature:5`

**Comment by phenaproxima** [comment]
For some reason, that test randomly fails quite frequently. Always that particular step of that particular test. Just restart the failed jobs, over and over until they pass. ;-)

That said, I just opened a new branch to update Multiversion and related modules (8.x-update-multiversion), which required some deep debugging in Multiversion and a new patch to be rolled. So that may render this PR moot...

**Comment by jeremdow** [comment]
Okay, thanks -

I'll try pulling that instead then, I was just keeping this branch open so the build I was working on doesn't fail to install.

**Pull request closed without merging**
