### PR TITLE
Resolves #99: Add phpcs to .travis.yml.

### LINKED ISSUE #99: Run phpcs in .travis.yml
This will require some code cleanup before it passes.

### PR DESCRIPTION
**Pull request by grasmash**

### CODE REVIEW

**Comment by grasmash** [comment]
This is failing for the right reasons--it is correctly finding coder issues.

**Comment by phenaproxima** [comment]
It also looks like PHPCS is trying to process CSS and JavaScript files. Can they be ignored as well?

**Comment by phenaproxima** [comment]
I have brought Lightning up to PHPCS's standards in another branch. Once that is merged, this should pass.

**Comment by phenaproxima** [comment]
I have merged this into the cleanup branch, with a couple of changes -- I'm ignoring all CSS files and the entire docroot tree (focusing only on the contents of the Lightning repo).

**Pull request closed without merging**
