### PR TITLE
Add Diff to Lightning

### PR DESCRIPTION
**Pull request by phenaproxima**
Diff has stabilized, and it's time to bring this incredibly useful module into Lightning. That's about it!

drupal.org issue: https://www.drupal.org/node/2762325

### CODE REVIEW

**Review by balsama — CHANGES_REQUESTED** [review]
This needs manual update instructions in UPDATE.md

**Review by balsama — COMMENTED** [review]
These step definitions are great, BTW. ++

**Review by balsama — APPROVED** [review]

**Review by balsama — CHANGES_REQUESTED** [review]
See https://www.drupal.org/node/2762325

**Comment by phenaproxima** [comment]
This was merged in 297f130d1f292ac1c4eded8c54e52e2821198450.

**Pull request closed without merging**
