### PR TITLE
Removed the band-aid patch for Panels in favor of using private tempstore

### PR DESCRIPTION
**Pull request by mortenson**
See #135

### CODE REVIEW

**Comment by mortenson** [comment]
Important note from the issue, as this does change behavior for existing Lightning users:

> Users who won't like this change are ones that are used to editing multiple unsaved Landing Pages (that were previously using the default) at once, but with Workbench Moderation they can just put a Landing Page into draft, make a change, save as custom, and go about their day.

**Comment by mortenson** [comment]
The test I modified is working - but the wizard tests are failing now. Not sure how we want to re-roll those, so I'm going to leave the PR open for Lightning team input.

Edit: Basically need to know if I should patch the Panelizer Wizard patch to use PrivateTempStore, or update the Drupal.org issue with an entirely new patch (which would delay that issue until https://www.drupal.org/node/2779813 is closed).

**Comment by balsama** [comment]
@mortenson I don't think we have a preference either way. This issue hasn't come up outside of this single report, so we're happy to wait for d.o#2779813 if that would be a more proper fix.

I'm happy to help reroll the tests too if the only reason they're failing is minor step changes. (not sure if that's the case or not)

**Comment by mortenson** [comment]
I tried patching the Panelizer default patch but it didn't pass tests - I'll need to roll back to the minimum commit (https://github.com/acquia/lightning/pull/145/commits/f07a820eac502e1712d1f5e07d1b144696353db9) and debug the errors manually.

**Comment by balsama** [comment]
Is there a chance these tests are failing due to slight changes in step definitions.

@mortenson you're more familiar with the exact changes. If you think that it's just minor changes (e.g. clicking here vs clicking there) I'm happy to manually test and adjust the tests accordingly.

**Comment by mortenson** [comment]
The only thing I'm intending to change is what TempStoreFactory Panels IPE (or the backend editors) use, so no test definitions need to change as the HTML Behat is interacting with should be unchanged.

I'm starting to think that because of the number of patches and dependencies involved with editing Panelizer defaults, I may have to think about this a bit more and implement a different solution. Even if PrivateTempStore was used and the tests pass, existing users would see newer, possibly weirder, behavior when using Panels IPE.

Tomorrow I'll draft an issue to discuss how we want to remove the bandaid, instead of plowing forward with this specific fix. We need to determine what behavior users expect when using Panels IPE + Panelizer + multiple defaults + multiple editors. There are a lot of edge cases to consider.

That said, I still think Panels IPE should use PrivateTempStore, so I'll keep the Drupal.org issue open regardless of what we decide on.

**Comment by mortenson** [comment]
Closing this for now as debugging the test failures and patch dependencies may be a bigger scope than this PR intended. The Panels issue is in (https://www.drupal.org/node/2779813), and we can carry the long-term band-aid removal discussion in the issue (#135).

**Pull request closed without merging**
